STATIC_GENRES = [{'genre': 'Literature & Fiction', 'count': 240826},
 {'genre': 'Kindle Short Reads', 'count': 128686},
 {'genre': 'Romance', 'count': 78012},
 {'genre': 'Genre Fiction', 'count': 68491},
 {'genre': 'Science Fiction & Fantasy', 'count': 51575},
 {'genre': 'Contemporary', 'count': 46815},
 {'genre': 'Religion & Spirituality', 'count': 42346},
 {'genre': 'Mystery, Thriller & Suspense', 'count': 39463},
 {'genre': 'Two hours or more (65-100 pages)', 'count': 35158},
 {'genre': 'Fantasy', 'count': 34580},
 {'genre': 'Erotica', 'count': 34023},
 {'genre': 'Health, Fitness & Dieting', 'count': 32549},
 {'genre': 'Contemporary Fiction', 'count': 29792},
 {'genre': '90 minutes (44-64 pages)', 'count': 28837},
 {'genre': "Children's eBooks", 'count': 25867},
 {'genre': "Children's Books", 'count': 25719},
 {'genre': 'Short Stories', 'count': 25169},
 {'genre': 'Science Fiction', 'count': 24573},
 {'genre': 'Thrillers & Suspense', 'count': 24559},
 {'genre': 'Christian Books & Bibles', 'count': 23801},
 {'genre': 'Self-Help', 'count': 23464},
 {'genre': 'Reference', 'count': 22249},
 {'genre': 'Action & Adventure', 'count': 21493},
 {'genre': 'Historical', 'count': 21136},
 {'genre': '45 minutes (22-32 pages)', 'count': 20964},
 {'genre': 'Mystery', 'count': 19242},
 {'genre': 'Biographies & Memoirs', 'count': 18836},
 {'genre': 'History', 'count': 18827},
 {'genre': 'One hour (33-43 pages)', 'count': 18647},
 {'genre': 'Business & Money', 'count': 18621},
 {'genre': 'Horror', 'count': 18334},
 {'genre': 'United States', 'count': 18213},
 {'genre': 'Fiction', 'count': 17843},
 {'genre': 'Teen & Young Adult', 'count': 16846},
 {'genre': '30 minutes (12-21 pages)', 'count': 16201},
 {'genre': 'Paranormal', 'count': 16181},
 {'genre': 'Suspense', 'count': 16094},
 {'genre': 'Humor', 'count': 15767},
 {'genre': 'Thrillers', 'count': 14252},
 {'genre': 'Humor & Entertainment', 'count': 13858},
 {'genre': 'Anthologies', 'count': 12578},
 {'genre': 'Single Author', 'count': 12338},
 {'genre': 'Romantic Erotica', 'count': 12311},
 {'genre': 'Professional & Technical', 'count': 12277},
 {'genre': 'Gay', 'count': 12271},
 {'genre': 'Gay & Lesbian', 'count': 12060},
 {'genre': 'Single Authors', 'count': 12050},
 {'genre': 'Cookbooks, Food & Wine', 'count': 11962},
 {'genre': 'Paranormal & Urban', 'count': 11515},
 {'genre': 'Arts & Photography', 'count': 11467},
 {'genre': 'Politics & Social Sciences', 'count': 11324},
 {'genre': 'Parenting & Relationships', 'count': 10963},
 {'genre': 'General', 'count': 10929},
 {'genre': 'Crafts, Hobbies & Home', 'count': 10520},
 {'genre': 'Crime', 'count': 10265},
 {'genre': 'Occult', 'count': 9692},
 {'genre': "Women's Fiction", 'count': 9608},
 {'genre': 'Education & Teaching', 'count': 8998},
 {'genre': 'Military', 'count': 8950},
 {'genre': 'Travel', 'count': 8905},
 {'genre': 'Foreign Languages', 'count': 8888},
 {'genre': '15 minutes (1-11 pages)', 'count': 8879},
 {'genre': 'Mystery & Suspense', 'count': 8673},
 {'genre': 'Spirituality', 'count': 8591},
 {'genre': 'Historical Fiction', 'count': 8519},
 {'genre': 'Sports & Outdoors', 'count': 8402},
 {'genre': 'Historical Romance', 'count': 8391},
 {'genre': 'Adventure', 'count': 8217},
 {'genre': 'Computers & Technology', 'count': 8001},
 {'genre': 'Education & Reference', 'count': 7947},
 {'genre': 'Literary', 'count': 7940},
 {'genre': 'Nonfiction', 'count': 7728},
 {'genre': 'Christian Living', 'count': 7687},
 {'genre': 'BDSM', 'count': 7527},
 {'genre': 'Science & Math', 'count': 7181},
 {'genre': 'Romantic Suspense', 'count': 6985},
 {'genre': 'Animals', 'count': 6945},
 {'genre': 'Humor & Satire', 'count': 6877},
 {'genre': 'Crime Fiction', 'count': 6859},
 {'genre': 'Sword & Sorcery', 'count': 6703},
 {'genre': 'Contemporary Women', 'count': 6524},
 {'genre': 'LGBT', 'count': 6307},
 {'genre': 'Christian Fiction', 'count': 6228},
 {'genre': 'Schools & Teaching', 'count': 6072},
 {'genre': 'Relationships', 'count': 5934},
 {'genre': 'Westerns', 'count': 5910},
 {'genre': 'Gay Romance', 'count': 5859},
 {'genre': 'General Humor', 'count': 5851},
 {'genre': 'Classics', 'count': 5814},
 {'genre': 'African American', 'count': 5736},
 {'genre': 'Americas', 'count': 5669},
 {'genre': 'Diets & Weight Loss', 'count': 5641},
 {'genre': 'Coming of Age', 'count': 5624},
 {'genre': 'Teacher Resources', 'count': 5591},
 {'genre': 'Poetry', 'count': 5389},
 {'genre': 'Medical Books', 'count': 5311},
 {'genre': 'Growing Up & Facts of Life', 'count': 5303},
 {'genre': 'Religious & Inspirational Fiction', 'count': 5266},
 {'genre': 'Love & Romance', 'count': 5254},
 {'genre': 'Memoirs', 'count': 5145},
 {'genre': 'Literary Fiction', 'count': 5137},
 {'genre': 'Collections & Anthologies', 'count': 5132},
 {'genre': 'Personal Transformation', 'count': 5040},
 {'genre': 'Epic', 'count': 5031},
 {'genre': 'Medical eBooks', 'count': 4972},
 {'genre': 'Europe', 'count': 4929},
 {'genre': 'New Age', 'count': 4860},
 {'genre': 'Diets', 'count': 4804},
 {'genre': 'Anthologies & Short Stories', 'count': 4790},
 {'genre': 'Family Life', 'count': 4765},
 {'genre': 'Science Fiction, Fantasy & Scary Stories', 'count': 4677},
 {'genre': 'Personal Growth', 'count': 4673},
 {'genre': 'Romantic Comedy', 'count': 4576},
 {'genre': 'Motivational', 'count': 4467},
 {'genre': 'Social Sciences', 'count': 4461},
 {'genre': 'Alternative Medicine', 'count': 4434},
 {'genre': 'Entrepreneurship & Small Business', 'count': 4428},
 {'genre': 'Comics & Graphic Novels', 'count': 4350},
 {'genre': 'Small Business & Entrepreneurship', 'count': 4340},
 {'genre': 'Personal Health', 'count': 4334},
 {'genre': 'Politics & Government', 'count': 4147},
 {'genre': 'Inspirational', 'count': 4132},
 {'genre': 'Mythology & Folk Tales', 'count': 4080},
 {'genre': 'Fairy Tales', 'count': 4075},
 {'genre': 'Series', 'count': 4054},
 {'genre': 'Urban', 'count': 3967},
 {'genre': 'Spanish', 'count': 3955},
 {'genre': 'Leaders & Notable People', 'count': 3939},
 {'genre': 'World', 'count': 3930},
 {'genre': 'Foreign Language Fiction', 'count': 3898},
 {'genre': 'Lesbian', 'count': 3863},
 {'genre': 'Drama', 'count': 3776},
 {'genre': 'New Adult & College', 'count': 3754},
 {'genre': 'Family Relationships', 'count': 3711},
 {'genre': 'Ghosts', 'count': 3663},
 {'genre': 'Special Diet', 'count': 3662},
 {'genre': 'Puzzles & Games', 'count': 3647},
 {'genre': 'Fantasy & Magic', 'count': 3629},
 {'genre': 'Drama & Plays', 'count': 3623},
 {'genre': 'Women Sleuths', 'count': 3572},
 {'genre': 'Crafts & Hobbies', 'count': 3533},
 {'genre': 'Holidays', 'count': 3494},
 {'genre': 'Bible Study & Reference', 'count': 3450},
 {'genre': 'Thriller', 'count': 3443},
 {'genre': 'Psychology & Counseling', 'count': 3417},
 {'genre': 'Werewolves & Shifters', 'count': 3408},
 {'genre': 'Weight Loss', 'count': 3360},
 {'genre': 'Graphic Novels', 'count': 3352},
 {'genre': 'Philosophy', 'count': 3322},
 {'genre': 'Words, Language & Grammar', 'count': 3286},
 {'genre': 'Management & Leadership', 'count': 3286},
 {'genre': 'Vampires', 'count': 3256},
 {'genre': 'Murder', 'count': 3208},
 {'genre': 'History & Criticism', 'count': 3207},
 {'genre': 'Pets & Animal Care', 'count': 3182},
 {'genre': 'Spies & Politics', 'count': 3129},
 {'genre': 'Writing, Research & Publishing Guides', 'count': 3112},
 {'genre': 'Engineering & Transportation', 'count': 3102},
 {'genre': 'Industries', 'count': 3063},
 {'genre': 'Western', 'count': 3045},
 {'genre': 'Industries & Professions', 'count': 3003},
 {'genre': 'Parenting', 'count': 2998},
 {'genre': 'Animal Care & Pets', 'count': 2993},
 {'genre': 'Supernatural', 'count': 2958},
 {'genre': 'Marketing & Sales', 'count': 2926},
 {'genre': 'Diseases & Physical Ailments', 'count': 2917},
 {'genre': 'Political', 'count': 2854},
 {'genre': 'Music', 'count': 2854},
 {'genre': 'Theology', 'count': 2840},
 {'genre': 'Religious', 'count': 2811},
 {'genre': 'Professionals & Academics', 'count': 2772},
 {'genre': 'Specific Groups', 'count': 2747},
 {'genre': 'Dystopian', 'count': 2737},
 {'genre': 'Disorders & Diseases', 'count': 2729},
 {'genre': 'Post-Apocalyptic', 'count': 2694},
 {'genre': 'Weight Maintenance', 'count': 2654},
 {'genre': 'Photography & Video', 'count': 2647},
 {'genre': 'Mental Health', 'count': 2643},
 {'genre': 'Regency', 'count': 2630},
 {'genre': 'Arts & Literature', 'count': 2607},
 {'genre': 'Multicultural', 'count': 2581},
 {'genre': 'Time Travel', 'count': 2542},
 {'genre': 'Friendship, Social Skills & School Life', 'count': 2523},
 {'genre': 'Photography', 'count': 2508},
 {'genre': 'Exercise & Fitness', 'count': 2478},
 {'genre': 'Other Diets', 'count': 2452},
 {'genre': 'War', 'count': 2437},
 {'genre': 'Professional Science', 'count': 2404},
 {'genre': 'Dogs', 'count': 2401},
 {'genre': 'Religious Studies & Reference', 'count': 2367},
 {'genre': 'Multicultural & Interracial', 'count': 2367},
 {'genre': 'Medicine', 'count': 2363},
 {'genre': 'Sagas', 'count': 2358},
 {'genre': 'Entrepreneurship', 'count': 2340},
 {'genre': 'Anthologies & Literary Collections', 'count': 2320},
 {'genre': 'Space Opera', 'count': 2305},
 {'genre': 'Education', 'count': 2259},
 {'genre': 'Cozy', 'count': 2253},
 {'genre': 'Religious Studies', 'count': 2241},
 {'genre': 'Psychological', 'count': 2227},
 {'genre': 'Domestic Life', 'count': 2212},
 {'genre': 'Education Theory', 'count': 2167},
 {'genre': 'Writing', 'count': 2141},
 {'genre': 'Family Saga', 'count': 2132},
 {'genre': 'German', 'count': 2119},
 {'genre': 'Internal Medicine', 'count': 2114},
 {'genre': 'Superheroes', 'count': 2107},
 {'genre': 'Linguistics', 'count': 2102},
 {'genre': 'War & Military', 'count': 2094},
 {'genre': 'True Crime', 'count': 2082},
 {'genre': 'True Accounts', 'count': 2064},
 {'genre': 'Psychological Thrillers', 'count': 2039},
 {'genre': 'Success', 'count': 2031},
 {'genre': 'Theater', 'count': 2010},
 {'genre': 'Asia', 'count': 1954},
 {'genre': 'Healthy Living', 'count': 1942},
 {'genre': 'Outdoors & Nature', 'count': 1941},
 {'genre': 'Art', 'count': 1914},
 {'genre': 'Business Life', 'count': 1912},
 {'genre': 'Specialty Travel', 'count': 1906},
 {'genre': 'Engineering', 'count': 1899},
 {'genre': 'Psychology', 'count': 1893},
 {'genre': 'Ministry & Evangelism', 'count': 1886},
 {'genre': 'Law', 'count': 1877},
 {'genre': 'Foreign Language Study & Reference', 'count': 1868},
 {'genre': 'Sports', 'count': 1864},
 {'genre': 'Language Instruction', 'count': 1814},
 {'genre': 'Dark Fantasy', 'count': 1792},
 {'genre': 'Hard-Boiled', 'count': 1790},
 {'genre': 'Studying & Workbooks', 'count': 1781},
 {'genre': 'Baking', 'count': 1779},
 {'genre': 'Fairy Tales, Folk Tales & Myths', 'count': 1773},
 {'genre': 'Individual Sports', 'count': 1748},
 {'genre': 'Spiritual Growth', 'count': 1734},
 {'genre': 'Women', 'count': 1732},
 {'genre': 'Anthologies & Literature Collections', 'count': 1721},
 {'genre': 'Biological Sciences', 'count': 1695},
 {'genre': 'Bedtime & Dreaming', 'count': 1687},
 {'genre': 'Specific Topics', 'count': 1673},
 {'genre': 'Criticism & Theory', 'count': 1670},
 {'genre': 'Police Procedurals', 'count': 1668},
 {'genre': 'Espionage', 'count': 1652},
 {'genre': 'Churches & Church Leadership', 'count': 1649},
 {'genre': 'Home Improvement & Design', 'count': 1630},
 {'genre': 'Activities, Crafts & Games', 'count': 1619},
 {'genre': 'Needlecrafts & Textile Crafts', 'count': 1613},
 {'genre': 'Meals', 'count': 1611},
 {'genre': 'State & Local', 'count': 1594},
 {'genre': 'Personal Finance', 'count': 1594},
 {'genre': 'High Tech', 'count': 1592},
 {'genre': 'Graphic Design', 'count': 1570},
 {'genre': 'Business & Management', 'count': 1564},
 {'genre': 'Marketing', 'count': 1563},
 {'genre': 'Sleep', 'count': 1562},
 {'genre': 'French', 'count': 1561},
 {'genre': 'Regional & International', 'count': 1560},
 {'genre': 'World Literature', 'count': 1559},
 {'genre': 'Hard Science Fiction', 'count': 1534},
 {'genre': 'Marriage', 'count': 1523},
 {'genre': 'Bible Study', 'count': 1522},
 {'genre': 'Home Based', 'count': 1510},
 {'genre': 'Home-Based', 'count': 1509},
 {'genre': 'Cooking by Ingredient', 'count': 1508},
 {'genre': 'British', 'count': 1496},
 {'genre': 'Devotionals', 'count': 1483},
 {'genre': 'Satire', 'count': 1478},
 {'genre': 'Gardening & Landscape Design', 'count': 1478},
 {'genre': 'Gardening & Horticulture', 'count': 1478},
 {'genre': 'Internet & Web Culture', 'count': 1475},
 {'genre': 'American', 'count': 1475},
 {'genre': 'Essays', 'count': 1473},
 {'genre': 'E-commerce', 'count': 1473},
 {'genre': 'Nature & Ecology', 'count': 1462},
 {'genre': 'Political Science', 'count': 1456},
 {'genre': 'Economics', 'count': 1442},
 {'genre': 'Special Occasions', 'count': 1441},
 {'genre': 'How-to & Home Improvements', 'count': 1440},
 {'genre': 'Skills', 'count': 1439},
 {'genre': 'Nutrition', 'count': 1433},
 {'genre': 'Biographies', 'count': 1424},
 {'genre': 'Witches & Wizards', 'count': 1420},
 {'genre': 'Main Courses & Side Dishes', 'count': 1413},
 {'genre': 'Great Britain', 'count': 1396},
 {'genre': 'Urban Life', 'count': 1385},
 {'genre': "Women's Health", 'count': 1379},
 {'genre': 'Encyclopedias & Subject Guides', 'count': 1376},
 {'genre': 'Business', 'count': 1365},
 {'genre': 'Training', 'count': 1347},
 {'genre': 'Entertaining & Holidays', 'count': 1347},
 {'genre': 'Actors & Entertainers', 'count': 1343},
 {'genre': 'Travelers & Explorers', 'count': 1337},
 {'genre': 'Regions', 'count': 1334},
 {'genre': 'Programming', 'count': 1332},
 {'genre': 'Beverages & Wine', 'count': 1317},
 {'genre': 'Performing Arts', 'count': 1311},
 {'genre': 'Angels', 'count': 1311},
 {'genre': 'Entertainers', 'count': 1296},
 {'genre': 'Actors & Actresses', 'count': 1296},
 {'genre': 'Leadership', 'count': 1276},
 {'genre': 'Metaphysical & Visionary', 'count': 1269},
 {'genre': 'Kindle Blogs', 'count': 1269},
 {'genre': 'Vegetables & Vegetarian', 'count': 1257},
 {'genre': 'Job Hunting & Careers', 'count': 1256},
 {'genre': 'England', 'count': 1242},
 {'genre': 'Writing Skills', 'count': 1235},
 {'genre': 'Paranormal & Fantasy', 'count': 1229},
 {'genre': 'Interpersonal Relations', 'count': 1215},
 {'genre': 'Investing', 'count': 1207},
 {'genre': 'Spiritual', 'count': 1201},
 {'genre': 'Accounting', 'count': 1201},
 {'genre': 'Serial Killers', 'count': 1199},
 {'genre': 'Games', 'count': 1194},
 {'genre': 'Paleo', 'count': 1189},
 {'genre': 'Interracial', 'count': 1185},
 {'genre': 'British Detectives', 'count': 1185},
 {'genre': 'Activity Books', 'count': 1183},
 {'genre': 'Self-Esteem', 'count': 1180},
 {'genre': 'World War II', 'count': 1176},
 {'genre': '20th Century', 'count': 1175},
 {'genre': 'Medieval', 'count': 1171},
 {'genre': 'Christian', 'count': 1169},
 {'genre': 'Finance', 'count': 1160},
 {'genre': 'Specialties', 'count': 1153},
 {'genre': 'Chapter Books & Readers', 'count': 1151},
 {'genre': 'Erotic Photography', 'count': 1150},
 {'genre': 'Happiness', 'count': 1146},
 {'genre': 'Quick & Easy', 'count': 1140},
 {'genre': 'Italian', 'count': 1133},
 {'genre': 'Holidays & Celebrations', 'count': 1124},
 {'genre': 'Medical', 'count': 1121},
 {'genre': 'Worship & Devotion', 'count': 1110},
 {'genre': 'Catholicism', 'count': 1108},
 {'genre': 'Web Development & Design', 'count': 1106},
 {'genre': 'Sex', 'count': 1106},
 {'genre': 'Vegetarian & Vegan', 'count': 1105},
 {'genre': 'Study Guides', 'count': 1091},
 {'genre': 'Low Fat', 'count': 1081},
 {'genre': 'Small Business', 'count': 1076},
 {'genre': 'Meditation', 'count': 1075},
 {'genre': 'Guides', 'count': 1073},
 {'genre': 'Death & Grief', 'count': 1072},
 {'genre': 'Web Marketing', 'count': 1060},
 {'genre': 'Love, Sex & Marriage', 'count': 1051},
 {'genre': 'Science, Nature & How It Works', 'count': 1045},
 {'genre': 'Alternate History', 'count': 1045},
 {'genre': 'Single Issue Comics', 'count': 1043},
 {'genre': 'Protestantism', 'count': 1042},
 {'genre': 'Alternative History', 'count': 1039},
 {'genre': 'Mysteries & Detectives', 'count': 1031},
 {'genre': 'Dysfunctional Relationships', 'count': 1028},
 {'genre': 'Lifestyle & Culture', 'count': 1011},
 {'genre': 'New Testament', 'count': 990},
 {'genre': 'Networking', 'count': 990},
 {'genre': 'Military & Spies', 'count': 982},
 {'genre': 'Historical Study & Educational Resources', 'count': 982},
 {'genre': 'Sociology', 'count': 973},
 {'genre': 'Demons & Devils', 'count': 970},
 {'genre': 'European', 'count': 966},
 {'genre': 'Management', 'count': 963},
 {'genre': 'Bibles', 'count': 963},
 {'genre': 'Christmas', 'count': 953},
 {'genre': 'Victorian', 'count': 950},
 {'genre': 'Gluten Free', 'count': 950},
 {'genre': 'Geography & Cultures', 'count': 946},
 {'genre': 'Ancient', 'count': 942},
 {'genre': 'Prayer', 'count': 941},
 {'genre': 'Mental & Spiritual Healing', 'count': 935},
 {'genre': 'Asian', 'count': 925},
 {'genre': 'Publishing & Books', 'count': 915},
 {'genre': 'Addiction & Recovery', 'count': 912},
 {'genre': 'Kitchen Appliances', 'count': 909},
 {'genre': 'Desserts', 'count': 908},
 {'genre': 'Book Notes', 'count': 908},
 {'genre': 'Games & Strategy Guides', 'count': 907},
 {'genre': 'Travel Writing', 'count': 903},
 {'genre': 'Cats', 'count': 901},
 {'genre': 'Christian Denominations & Sects', 'count': 898},
 {'genre': 'Comedy', 'count': 896},
 {'genre': 'Hiking & Camping', 'count': 891},
 {'genre': 'Astronomy & Space Science', 'count': 890},
 {'genre': 'Drinks & Beverages', 'count': 879},
 {'genre': 'Advertising', 'count': 878},
 {'genre': 'Psychics', 'count': 875},
 {'genre': 'Techniques', 'count': 873},
 {'genre': 'Commentaries', 'count': 868},
 {'genre': 'Physics', 'count': 866},
 {'genre': 'Allergies', 'count': 866},
 {'genre': 'Beauty & Fashion', 'count': 864},
 {'genre': 'Murder & Mayhem', 'count': 861},
 {'genre': 'Hunting & Fishing', 'count': 861},
 {'genre': 'Other Religions, Practices & Sacred Texts', 'count': 860},
 {'genre': 'Musical Genres', 'count': 858},
 {'genre': 'Beauty, Grooming, & Style', 'count': 858},
 {'genre': 'Spine-Chilling Horror', 'count': 852},
 {'genre': 'Cooking Methods', 'count': 849},
 {'genre': 'Healing', 'count': 848},
 {'genre': 'Friendship', 'count': 845},
 {'genre': 'Ancient Civilizations', 'count': 841},
 {'genre': 'Judaism', 'count': 837},
 {'genre': 'Transportation', 'count': 836},
 {'genre': 'Metaphysical', 'count': 836},
 {'genre': 'Jewish', 'count': 834},
 {'genre': 'Video Games', 'count': 833},
 {'genre': 'Test Preparation', 'count': 826},
 {'genre': 'Essays & Travelogues', 'count': 825},
 {'genre': 'Miscellaneous', 'count': 824},
 {'genre': 'British & Irish', 'count': 824},
 {'genre': 'Crime & Criminals', 'count': 820},
 {'genre': 'Civil War', 'count': 819},
 {'genre': 'Steampunk', 'count': 817},
 {'genre': 'Stress Management', 'count': 816},
 {'genre': 'New Thought', 'count': 816},
 {'genre': 'Ethnic & National', 'count': 814},
 {'genre': 'Earth Sciences', 'count': 814},
 {'genre': 'Childhood Education', 'count': 814},
 {'genre': 'Lesbian Romance', 'count': 809},
 {'genre': 'Babies & Toddlers', 'count': 801},
 {'genre': 'Early Childhood', 'count': 796},
 {'genre': 'Beginner Readers', 'count': 796},
 {'genre': 'Organized Crime', 'count': 790},
 {'genre': 'Humorous', 'count': 787},
 {'genre': 'International & World Politics', 'count': 785},
 {'genre': 'Technothrillers', 'count': 782},
 {'genre': 'Superhero', 'count': 781},
 {'genre': 'Mathematics', 'count': 781},
 {'genre': 'Movies', 'count': 777},
 {'genre': 'Short Story Collections', 'count': 774},
 {'genre': 'Diseases', 'count': 770},
 {'genre': 'Sales & Selling', 'count': 767},
 {'genre': 'Video & Electronic Games', 'count': 766},
 {'genre': 'Girls & Women', 'count': 765},
 {'genre': 'Adventurers & Explorers', 'count': 765},
 {'genre': 'Private Investigators', 'count': 763},
 {'genre': 'Accounting & Finance', 'count': 763},
 {'genre': 'Theory, Composition & Performance', 'count': 756},
 {'genre': 'South', 'count': 756},
 {'genre': 'Genetic Engineering', 'count': 754},
 {'genre': '19th Century', 'count': 751},
 {'genre': 'Christianity', 'count': 744},
 {'genre': 'Horses', 'count': 743},
 {'genre': 'Terrorism', 'count': 741},
 {'genre': 'Electronics', 'count': 739},
 {'genre': 'Crocheting', 'count': 739},
 {'genre': 'Arts & Entertainment', 'count': 738},
 {'genre': 'Portuguese', 'count': 734},
 {'genre': 'Divorce', 'count': 734},
 {'genre': 'Movies & Video', 'count': 728},
 {'genre': 'Myths & Legends', 'count': 721},
 {'genre': "Men's Adventure", 'count': 718},
 {'genre': 'Scary Stories', 'count': 715},
 {'genre': 'Recovery', 'count': 715},
 {'genre': 'Budgeting & Money Management', 'count': 711},
 {'genre': 'France', 'count': 708},
 {'genre': 'Specific Demographics', 'count': 707},
 {'genre': 'Native American', 'count': 703},
 {'genre': 'Family', 'count': 701},
 {'genre': 'Job Hunting', 'count': 700},
 {'genre': 'Mysticism', 'count': 695},
 {'genre': 'Kindle Accessories', 'count': 695},
 {'genre': 'Inspirational & Religious', 'count': 694},
 {'genre': 'Real Estate', 'count': 691},
 {'genre': 'Space Fleet', 'count': 689},
 {'genre': 'Healthy', 'count': 689},
 {'genre': 'Environment', 'count': 689},
 {'genre': 'Aviation', 'count': 687},
 {'genre': 'Africa', 'count': 687},
 {'genre': 'Early Childhood Education', 'count': 685},
 {'genre': 'Higher & Continuing Education', 'count': 683},
 {'genre': 'Emotions & Feelings', 'count': 678},
 {'genre': 'Scottish', 'count': 672},
 {'genre': 'Bisexual', 'count': 665},
 {'genre': 'Gothic', 'count': 664},
 {'genre': 'Meditations', 'count': 663},
 {'genre': 'Vegan', 'count': 661},
 {'genre': 'Alien Invasion', 'count': 661},
 {'genre': 'Unexplained Mysteries', 'count': 659},
 {'genre': 'Authorship', 'count': 659},
 {'genre': 'Career Guides', 'count': 658},
 {'genre': 'Alternative & Holistic', 'count': 657},
 {'genre': 'West', 'count': 655},
 {'genre': 'Jokes & Riddles', 'count': 652},
 {'genre': 'Manga', 'count': 650},
 {'genre': 'By Technique', 'count': 650},
 {'genre': 'Breeds', 'count': 650},
 {'genre': 'Biographical', 'count': 649},
 {'genre': 'Food, Lodging & Transportation', 'count': 647},
 {'genre': 'Research', 'count': 643},
 {'genre': 'Time Management', 'count': 641},
 {'genre': 'Mental Illness', 'count': 640},
 {'genre': 'Automotive', 'count': 637},
 {'genre': 'Technology', 'count': 635},
 {'genre': 'Movements & Periods', 'count': 635},
 {'genre': 'Internet, Groupware, & Telecommunications', 'count': 635},
 {'genre': 'Rich & Famous', 'count': 634},
 {'genre': 'Church History', 'count': 634},
 {'genre': 'Old Testament', 'count': 633},
 {'genre': 'Sea Adventures', 'count': 629},
 {'genre': 'Water Sports', 'count': 626},
 {'genre': 'Investing Basics', 'count': 623},
 {'genre': 'Authors', 'count': 621}]

