"""empty message

Revision ID: 1bd410563c09
Revises: 
Create Date: 2019-11-29 02:29:44.316046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bd410563c09'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asin', sa.String(length=20), nullable=False),
    sa.Column('helpful_rating', sa.Integer(), nullable=True),
    sa.Column('total_helpful_rating', sa.Integer(), nullable=True),
    sa.Column('review_rating', sa.Integer(), nullable=True),
    sa.Column('review_text', sa.TEXT(), nullable=True),
    sa.Column('summary_text', sa.String(length=15000), nullable=True),
    sa.Column('username', sa.String(length=200), nullable=True),
    sa.Column('reviewer_id', sa.String(length=200), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.Column('unix_timestamp', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historical_reviews_asin'), 'historical_reviews', ['asin'], unique=False)
    op.create_table('revoked_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('live_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=True),
    sa.Column('asin', sa.String(length=20), nullable=False),
    sa.Column('review_rating', sa.FLOAT(), nullable=True),
    sa.Column('review_text', sa.TEXT(), nullable=True),
    sa.Column('unix_timestamp', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asin', 'username', name='asin_username_constraint')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('live_reviews')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('revoked_tokens')
    op.drop_index(op.f('ix_historical_reviews_asin'), table_name='historical_reviews')
    op.drop_table('historical_reviews')
    # ### end Alembic commands ###
