"""empty message

Revision ID: 2042765efe4c
Revises: 9879f4522133
Create Date: 2019-10-17 23:39:09.892758

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2042765efe4c'
down_revision = '9879f4522133'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=120),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=120),
               nullable=False)
    # ### end Alembic commands ###
