"""empty message

Revision ID: 9e22e09c0d1c
Revises: ca104721cf40
Create Date: 2019-10-30 11:55:09.638681

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9e22e09c0d1c'
down_revision = 'ca104721cf40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historical_reviews', sa.Column('username', sa.String(length=200), nullable=True))
    op.drop_column('historical_reviews', 'reviewer_name')
    op.add_column('live_reviews', sa.Column('username', sa.String(length=200), nullable=True))
    op.drop_constraint('asin_username_constraint', 'live_reviews', type_='unique')
    op.create_unique_constraint('asin_username_constraint', 'live_reviews', ['asin', 'username'])
    op.drop_constraint('live_reviews_ibfk_1', 'live_reviews', type_='foreignkey')
    op.create_foreign_key(None, 'live_reviews', 'users', ['username'], ['username'])
    op.drop_column('live_reviews', 'reviewer_username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('live_reviews', sa.Column('reviewer_username', mysql.VARCHAR(collation='utf8mb4_general_ci', length=200), nullable=True))
    op.drop_constraint(None, 'live_reviews', type_='foreignkey')
    op.create_foreign_key('live_reviews_ibfk_1', 'live_reviews', 'users', ['reviewer_username'], ['username'])
    op.drop_constraint('asin_username_constraint', 'live_reviews', type_='unique')
    op.create_unique_constraint('asin_username_constraint', 'live_reviews', ['asin', 'reviewer_username'])
    op.drop_column('live_reviews', 'username')
    op.add_column('historical_reviews', sa.Column('reviewer_name', mysql.VARCHAR(collation='utf8mb4_general_ci', length=200), nullable=True))
    op.drop_column('historical_reviews', 'username')
    # ### end Alembic commands ###
