"""empty message

Revision ID: ca104721cf40
Revises: 2e94a74ff150
Create Date: 2019-10-30 10:16:45.975464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca104721cf40'
down_revision = '2e94a74ff150'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('asin_username_constraint', 'live_reviews', ['asin', 'reviewer_username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('asin_username_constraint', 'live_reviews', type_='unique')
    # ### end Alembic commands ###
